DocSystem_New:
  image: registry.cn-hangzhou.aliyuncs.com/docsystem/docsystem:v0.13
  privileged: false
  restart: always
  ports:
    - 8181:8181
  volumes:
    - /var/www/docsystem/database:/docsystem/database
    - /var/www/docsystem/uploads:/docsystem/uploads
  environment:
    - DOCSYSTEM_RUN_MODE=prod
    - DOCSYSTEM_DB_ADAPTER=sqlite3
    - DOCSYSTEM_DB_DATABASE=./database/docsystem.db
    - DOCSYSTEM_CACHE=true
    - DOCSYSTEM_CACHE_PROVIDER=file
    - DOCSYSTEM_ENABLE_EXPORT=false
    - DOCSYSTEM_BASE_URL=
    - DOCSYSTEM_CDN_IMG_URL=
    - DOCSYSTEM_CDN_CSS_URL=
    - DOCSYSTEM_CDN_JS_URL=
  dns:
    - 223.5.5.5
    - 223.6.6.6